name: Auto Build on Tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production
  build_ios:
    type: build
    params:
      platform: ios
      profile: production
