name: Deploy Updates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_updates:
    type: update
    params:
      branch: main
      message: "Auto-deploy from CI/CD - ${{ github.event.head_commit.message }}"
